{
 "title": "Scope Measurements",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "link",
    "label": "WR link",
    "query": "SHOW TAG VALUES WITH KEY = \"link\""
   },
   {
    "name": "hostname",
    "label": "WRS",
    "query": "SHOW TAG VALUES WITH KEY = \"agent_host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "shack" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "shack" }
     ]
    }
   ]
  },
  {
   "title": "Round Trip Time (WR slave = $hostname)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RTT",
     "measurement": "wrsPtpDataTable",
     "select": [
      [
       { "params": [ "wrsPtpRTT" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "PPS Skew ($link)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Skew",
     "measurement": "timing",
     "select": [
      [
       { "params": [ "skew" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "link", "operator": "=~", "value": "/^$link$/" }
     ]
    }
   ]
  },
  {
   "title": "Skew (WR slave = $hostname)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Skew",
     "measurement": "wrsPtpDataTable",
     "select": [
      [
       { "params": [ "wrsPtpSkew" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Spread",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "wrsPtpDataTable",
     "select": [
      [
       { "params": [ "wrsPtpSkew" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "30" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "PPS skew rms ($link)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RMS (skew)",
     "measurement": "timing",
     "select": [
      [
       { "params": [ "skewrms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "link", "operator": "=~", "value": "/^$link$/" }
     ]
    },
    {
     "alias": "Mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timing",
     "select": [
      [
       { "params": [ "skewrms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "link", "operator": "=~", "value": "/^$link$/" }
     ]
    }
   ]
  }
 ]
}